name: retake
channels:
  - defaults
dependencies:
  - python==3.11
  - pip:
      - torch==2.4.0
      - torchvision==0.19.0
      - transformers==4.48
      - accelerate==0.34.2
      - flash-attn==2.6.3
      - av==13.1.0
      - pyyaml==6.0.2
      - opencv-python-headless==4.10.0.84
      - pandas==2.2.3
      - pysubs2==1.7.3
      - pyarrow==17.0.0
      - openai==1.56.0