### model
method: retake
scaling_factor: 4
attn_implementation: "flash_attention_2"

### dataset
dataset_name: mlvu
anno_file: dataset/mlvu/mlvu.json
dataloader_num_workers: 2

### data
sample_fps: 4
max_num_frames: 256
longsize_resolution: 448

### generate
do_sample: false

### output
output_dir: results/qwen2vl_7b_mlvu_f256_4fps_r448/base
