### model
model_name: qwen2_vl
method: retake
scaling_factor: 4
attn_implementation: "flash_attention_2"

### dataset
dataset_name: videomme
anno_file: dataset/video_mme/video_mme.json
dataloader_num_workers: 2

### data
sample_fps: 4
max_num_frames: 256
longsize_resolution: 448

### generate
do_sample: false

### output
output_dir: results/qwen2vl_7b_videomme_f256_4fps_r448/base
