### model
method: retake
scaling_factor: 4
attn_implementation: "eager" # NPU does not support sdpa attention now
longvideo_kwargs: {
  'frame_chunk_size': 16, # Trade-off beteen peak memory and speed
  'chunked_prefill_frames': 16, # Trade-off beteen peak memory and speed
  # Keyframe compression
  'visual_compression': True,
  'visual_compression_kwargs': {
    'compression_ratio': 1.0,
    'compression_method': 'Keyframe',
    'patch_sync': False,
    'return_keyframe_mask': True
  },
  # KVCache compression
  'kvcache_compression': True,
  'kvcache_compression_kwargs': {
    'dynamic_compression_ratio': True,
    'compression_method': 'pivotkv',
    'pos_embed_reforge': True,
    'max_input_length': 32000
  },
}

### data
sample_fps: 4
max_num_frames: 2048
longsize_resolution: 448

### generate
do_sample: false